### ISSUE TITLE
Properly construct and validate URLs embedded on generated code

### ISSUE THREAD

**Issue by dieggsy** [Tevo45/juniper#4]
Possibly a failing of the particular swagger spec I've been using, but in the generated code for e.g. `get-characters-character-id-skillqueue`, I see something like this, notice the double `//`:

```lisp
(#1=#:URL2142 "https://esi.evetech.net//v2/characters/{character_id}/skillqueue/")
```
And I get a not found error. It's possible that the cause for this is in [the following code](https://github.com/Tevo45/juniper/blob/master/juniper.lisp#L160):
```lisp
(defun swagger-path-bindings (path &aux (name (car path)) (ops (cdr path)))
  (let* ((*endpoint* (string name))
	 ; FIXME we have puri as a dependency and still construct urls by hand
	 (*url* (format nil "~a://~a~a~a" *proto* *host* *base-path* *endpoint*))
	 (*path-params* (field :|parameters| ops)))
    `(progn
       ,@(mapcar #'function-for-op ops))))
```

**Comment by dieggsy** [comment]
Hmmm, looking at this further, it's possible this is caused by the line `(*base-path* (or base-path (field :|basePath|) "/"))` in `bindings-from-stream`. I think it might be safe to remove the `"/"` here, as a path will start with `/` anyway from what I can tell.

**Comment by Tevo45** [comment]
Yeah; that's probably the issue; the swagger spec specifies that `/` is assumed when the schema doesn't specify a basePath, but since we just "construct" paths by mashing the strings together you'll end up with a double slash, which the remote server may or may not like (unsure how it's intended to behave). Defaulting to an empty string would probably fix it for schemas without a basePath, but does no good for schemas that for some reason specify `/` explicitly, which ought to be legal.

I've changed the default to "", which should work around the issue for now; but I need to find a better way to construct those paths later, so that we can "reroot" paths to the base path while avoiding double slashes and such things, set specific url parts while ensuring it still is a valid url, etc. Puri (which we already have as a dependency) can do some of that, but it seems to choke on {} which are invalid on actual urls (it seems) but used for path parameters; I'd need to figure out how to either allow for curly braces on the parsed urls or devise my own solution or something.

**Comment by dieggsy** [comment]
@Tevo45 wouldn't that just be a matter of doing the parameter replacement on the path before constructing a url ?

**Comment by Tevo45** [comment]
> @Tevo45 wouldn't that just be a matter of doing the parameter replacement on the path before constructing a url?

Yeah, actually. I'm rather silly and didn't thought of it, thanks and sorry for that. I've changed the generator to construct the urls at the generated function's runtime, after replacing the path parameters; I'm also filtering empty path components explicitly, as to avoid double-slashes anywhere in the path. 

I've done some manual testing and it seems fine but please let me know if anything breaks; I'll get around to writing a proper test suite hopefully soon.

**Comment by dieggsy** [comment]
I appreciate that, thanks! - it might make sense to use (make-instance 'puri:uri :scheme ... :host ...) instead of `(puri:uri "")` and `setf`-ing everything.
